### ISSUE TITLE
Error when trying to download

### ISSUE THREAD

**Issue by rnt999** [JKair/youkuDownload#1]
Hello,

I am trying to download youku video from url: http://v.youku.com/v_show/id_XMTI3MjI3MzI2NA==.html?f=23300495&ev=2
 and geting error: "The remote name could not be resolved: 'f.youku.com'"

**Comment by JKair** [comment]
sorry,I find your issues on this time.
Youku disabled this api what I use to download,I dont update this project when I finished.
You can use [you-get](https://github.com/soimort/you-get) if you want to download movie.
thanks for you issues
